global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask_app'
    static_configs:
      - targets: ['app:8000']

  - job_name: 'docker_metrics'
    static_configs:
      - targets: ['pushgateway:9091']
